// 端到端集成测试：install.rs 的全部 MySQL DDL
// 经 db_ddl 转换后在真 SQLite 内存库执行，验证转换器对真实业务 DDL 的覆盖。

use sqlx::sqlite::SqlitePoolOptions;
use nakamasa_utils::db_ddl::adapt_ddl_mysql_to_sqlite;

// 直接从 install.rs 提取的真实 DDL（{p} 替换为 "t"）
const TABLES: &[&str] = &[
    r#"CREATE TABLE IF NOT EXISTS `t_admin` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `user` varchar(18) NOT NULL,
            `password` varchar(255) NOT NULL COMMENT 'Argon2id 或兼容旧 MD5 哈希',
            `notes` varchar(64) NOT NULL,
            `avatars` varchar(128) DEFAULT NULL,
            `lockin` tinyint(1) DEFAULT '0',
            `auth` json DEFAULT NULL,
            `state` enum('y','n') DEFAULT 'y',
            `appid` json DEFAULT NULL,
            PRIMARY KEY (`id`),
            UNIQUE KEY `user` (`user`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_app` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `app_key` varchar(32) NOT NULL,
            `app_type` enum('user','kami') NOT NULL,
            `app_name` varchar(64) NOT NULL,
            `app_logo` varchar(64) DEFAULT NULL,
            `app_mode` enum('y','n') DEFAULT 'y',
            `app_state` enum('on','off') DEFAULT 'on',
            `app_off_msg` varchar(255) DEFAULT NULL,
            `reg_state` enum('on','off') DEFAULT 'on',
            `reg_off_msg` varchar(255) DEFAULT NULL,
            `reg_way` enum('phone','email','wordnum') DEFAULT 'email',
            `reg_is_inviter` enum('y','n') DEFAULT 'n',
            `reg_time_sn` int(10) DEFAULT '24',
            `reg_time_ip` int(10) DEFAULT '24',
            `reg_award` enum('vip','fen') DEFAULT 'vip',
            `reg_award_val` bigint(10) DEFAULT '86400',
            `logon_state` enum('on','off') DEFAULT 'on',
            `logon_off_msg` varchar(255) DEFAULT NULL,
            `logon_open_wxconfig` json DEFAULT NULL,
            `logon_open_qqconfig` json DEFAULT NULL,
            `logon_token_exp` int(10) DEFAULT '86400',
            `logon_ban_expire` enum('y','n') DEFAULT 'y',
            `logon_sn_dk` enum('y','n') DEFAULT 'n',
            `logon_sn_num` int(2) DEFAULT '0',
            `logon_sn_over_ban` tinyint(1) DEFAULT '1',
            `login_prevent_brute_force` tinyint(1) DEFAULT '1',
            `logon_sn_unbde_auto` tinyint(1) DEFAULT '0',
            `logon_sn_unbde_type` enum('vip','fen') DEFAULT 'fen',
            `logon_sn_unbde_val` int(10) DEFAULT '100',
            `face_enable` enum('on','off') DEFAULT 'off' COMMENT '是否开启人脸识别安全验证 on/off',
            `invitee_award` enum('vip','fen') DEFAULT 'vip',
            `invitee_award_val` int(10) DEFAULT '43200',
            `inviter_award` enum('vip','fen') DEFAULT 'vip',
            `inviter_award_val` int(10) DEFAULT '86400',
            `diary_award` enum('vip','fen') DEFAULT 'fen',
            `diary_award_val` int(10) DEFAULT '100',
            `smtp_state` enum('on','off') DEFAULT 'off',
            `smtp_host` varchar(128) DEFAULT 'smtp.qq.com',
            `smtp_user` varchar(128) DEFAULT NULL,
            `smtp_pass` varchar(128) DEFAULT NULL,
            `smtp_port` int(4) DEFAULT '465',
            `sms_state` enum('on','off') DEFAULT 'off',
            `sms_type` varchar(24) DEFAULT 'jie',
            `sms_config` json DEFAULT NULL,
            `vc_time` int(2) DEFAULT '10',
            `vc_length` int(1) DEFAULT '4',
            `vc_frequency` int(5) DEFAULT '120',
            `vc_maximum` int(2) DEFAULT '10',
            `pay_ali_state` enum('on','off') DEFAULT 'off',
            `pay_ali_type` varchar(24) DEFAULT 'jie',
            `pay_ali_config` json DEFAULT NULL,
            `pay_wx_state` enum('on','off') DEFAULT 'off',
            `pay_wx_type` varchar(24) DEFAULT 'jie',
            `pay_wx_config` json DEFAULT NULL,
            `pay_qqpay_state` enum('on','off') DEFAULT 'off',
            `pay_qqpay_type` varchar(24) DEFAULT 'jie',
            `pay_qqpay_config` json DEFAULT NULL,
            `pay_paypal_state` enum('on','off') DEFAULT 'off',
            `pay_paypal_type` varchar(24) DEFAULT 'jie',
            `pay_paypal_config` json DEFAULT NULL,
            `ai_state` enum('on','off') DEFAULT 'off',
            `ai_provider` varchar(32) DEFAULT NULL,
            `ai_api_base` varchar(255) DEFAULT NULL,
            `ai_api_key` text DEFAULT NULL,
            `ai_model` varchar(128) DEFAULT NULL,
            `ai_temperature` float DEFAULT NULL,
            `ai_max_tokens` int(10) DEFAULT NULL,
            `api_router` json DEFAULT NULL COMMENT '用户端自定义 API 路由（为空或 default 走内置路由）',
            `api_code` text DEFAULT NULL COMMENT '用户端自定义 API 代码',
            PRIMARY KEY (`id`),
            UNIQUE KEY `app_key` (`app_key`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_user` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `email` varchar(64) DEFAULT NULL,
            `phone` bigint(11) DEFAULT NULL,
            `acctno` varchar(18) DEFAULT NULL,
            `nickname` varchar(128) DEFAULT NULL,
            `avatars` varchar(255) DEFAULT NULL,
            `password` varchar(255) NOT NULL COMMENT 'Argon2id 或兼容旧 MD5 哈希',
            `inviter_id` bigint(20) DEFAULT NULL,
            `vip` bigint(10) DEFAULT NULL,
            `fen` bigint(10) DEFAULT '0',
            `extend` json DEFAULT NULL,
            `open_wx` varchar(128) DEFAULT NULL,
            `open_qq` varchar(128) DEFAULT NULL,
            `face_embedding` blob DEFAULT NULL COMMENT '人脸特征向量(512维f32,2048字节)',
            `face_image` varchar(255) DEFAULT NULL COMMENT '人脸底图路径(开启保留底图时写入)',
            `face_time` bigint(10) DEFAULT NULL COMMENT '人脸注册时间',
            `last_location` varchar(128) DEFAULT NULL COMMENT '最近登录地',
            `last_login_ip` varchar(45) DEFAULT NULL COMMENT '最近登录IP',
            `reg_time` bigint(10) NOT NULL,
            `reg_ip` varchar(45) NOT NULL,
            `reg_sn` varchar(64) DEFAULT NULL,
            `sn_list` json DEFAULT NULL,
            `sn_max` bigint(2) DEFAULT '0',
            `ban` bigint(10) DEFAULT NULL,
            `ban_msg` varchar(255) DEFAULT NULL,
            `appid` bigint(20) NOT NULL,
            PRIMARY KEY (`id`),
            UNIQUE KEY `email_appid` (`email`,`appid`),
            UNIQUE KEY `phone_appid` (`phone`,`appid`),
            UNIQUE KEY `acctno_appid` (`acctno`,`appid`),
            UNIQUE KEY `open_wx_appid` (`open_wx`,`appid`),
            UNIQUE KEY `open_qq_appid` (`open_qq`,`appid`),
            KEY `appid` (`appid`),
            KEY `inviter_id` (`inviter_id`),
            KEY `reg_ip` (`reg_ip`),
            KEY `ban` (`ban`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_login` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `uid` bigint(20) NOT NULL,
            `token` varchar(32) NOT NULL,
            `sn` varchar(128) DEFAULT NULL,
            `ip` varchar(45) DEFAULT NULL,
            `time` bigint(10) NOT NULL,
            `appid` bigint(20) NOT NULL,
            PRIMARY KEY (`id`),
            UNIQUE KEY `token` (`token`),
            KEY `uid` (`uid`),
            KEY `sn` (`sn`),
            KEY `appid` (`appid`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_logs` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `ug` enum('admin','agent','user','kami') NOT NULL,
            `uid` bigint(20) NOT NULL,
            `type` varchar(64) NOT NULL,
            `details` json DEFAULT NULL,
            `asset_changes` json DEFAULT NULL,
            `state` varchar(2) DEFAULT NULL,
            `time` bigint(10) NOT NULL,
            `ip` varchar(45) NOT NULL,
            `ip_address` varchar(128) DEFAULT NULL,
            `appid` bigint(20) DEFAULT NULL,
            PRIMARY KEY (`id`),
            KEY `appid` (`appid`),
            KEY `ug` (`ug`),
            KEY `uid` (`uid`),
            KEY `type` (`type`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_goods` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `name` varchar(128) NOT NULL,
            `type` enum('vip','fen','agent','addsn') NOT NULL,
            `val` bigint(20) NOT NULL,
            `money` bigint(20) NOT NULL COMMENT '金额（分）',
            `blurb` text,
            `state` enum('y','n') DEFAULT 'y',
            `appid` bigint(20) NOT NULL,
            PRIMARY KEY (`id`),
            KEY `appid` (`appid`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_order` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `uid` bigint(20) NOT NULL,
            `gid` bigint(20) NOT NULL,
            `inviter_id` bigint(20) DEFAULT NULL,
            `order_no` varchar(40) NOT NULL,
            `trade_no` varchar(60) DEFAULT NULL,
            `name` varchar(128) NOT NULL,
            `money` bigint(20) NOT NULL COMMENT '实付金额（分）',
            `divide_money` bigint(20) DEFAULT NULL COMMENT '代理分成（分）',
            `type` varchar(12) NOT NULL,
            `val` bigint(20) NOT NULL,
            `payment` enum('ali','wx') DEFAULT NULL,
            `add_time` bigint(10) NOT NULL,
            `end_time` bigint(10) DEFAULT NULL,
            `state` int(1) DEFAULT '0',
            `appid` bigint(20) NOT NULL,
            PRIMARY KEY (`id`),
            KEY `inviter_id` (`inviter_id`),
            KEY `type` (`type`),
            KEY `ptype` (`payment`),
            KEY `appid` (`state`,`appid`),
            KEY `uid` (`uid`),
            KEY `gid` (`gid`),
            KEY `order_no` (`order_no`),
            KEY `trade_no` (`trade_no`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_vcode` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `eorp` varchar(64) NOT NULL,
            `type` varchar(12) NOT NULL,
            `code` int(6) NOT NULL,
            `usable` enum('y','n') DEFAULT 'y',
            `time` bigint(10) NOT NULL,
            `ip` varchar(45) NOT NULL,
            `appid` bigint(20) NOT NULL,
            PRIMARY KEY (`id`),
            KEY `eorp` (`eorp`),
            KEY `type` (`type`),
            KEY `code` (`code`),
            KEY `appid` (`appid`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_message` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `uid` bigint(20) NOT NULL,
            `utype` enum('user','admin') NOT NULL,
            `title` varchar(128) DEFAULT NULL,
            `content` text NOT NULL,
            `reply_id` bigint(20) DEFAULT NULL,
            `file` json DEFAULT NULL,
            `time` bigint(10) NOT NULL,
            `last_time` bigint(10) DEFAULT NULL,
            `state` int(1) DEFAULT '0',
            `appid` bigint(20) NOT NULL,
            PRIMARY KEY (`id`),
            KEY `utype` (`utype`),
            KEY `title` (`title`),
            KEY `reply_id` (`reply_id`),
            KEY `state` (`state`),
            KEY `appid` (`appid`),
            KEY `uid` (`uid`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_cdk_group` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `name` varchar(64) NOT NULL,
            `val` bigint(10) NOT NULL,
            `type` enum('vip','fen','addsn') NOT NULL,
            `price` float(10,2) DEFAULT NULL,
            `appid` bigint(20) NOT NULL,
            PRIMARY KEY (`id`),
            KEY `appid` (`appid`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_cdk_kami` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `gid` bigint(20) NOT NULL,
            `type` enum('vip','fen','addsn') NOT NULL,
            `cdk` varchar(64) NOT NULL,
            `val` bigint(10) NOT NULL,
            `email` varchar(64) DEFAULT NULL,
            `phone` bigint(11) DEFAULT NULL,
            `password` varchar(255) DEFAULT NULL COMMENT 'Argon2id/MD5 卡密密码，卡密登录成功后原地升级',
            `note` varchar(128) DEFAULT NULL,
            `vip` bigint(10) DEFAULT NULL,
            `fen` bigint(10) DEFAULT NULL,
            `add_role` enum('admin','agent') NOT NULL,
            `add_uid` bigint(20) NOT NULL,
            `add_price` float(10,2) DEFAULT '0.00',
            `add_time` int(10) NOT NULL,
            `add_ip` varchar(45) NOT NULL,
            `use_id` bigint(20) DEFAULT NULL,
            `use_time` bigint(10) DEFAULT NULL,
            `use_ip` varchar(45) DEFAULT NULL,
            `out_state` enum('y','n') DEFAULT 'n',
            `out_time` bigint(10) DEFAULT NULL,
            `ban` bigint(10) DEFAULT NULL,
            `ban_msg` varchar(128) DEFAULT NULL,
            `sn_max` int(2) DEFAULT '0',
            `sn_list` json DEFAULT NULL,
            `extend` json DEFAULT NULL COMMENT '用户自定义扩展字段（与 u_user.extend 对应）',
            `appid` bigint(20) NOT NULL,
            PRIMARY KEY (`id`),
            UNIQUE KEY `cdk` (`cdk`,`appid`),
            UNIQUE KEY `phone` (`phone`,`appid`),
            UNIQUE KEY `email` (`email`,`appid`),
            KEY `gid` (`gid`),
            KEY `add_uid` (`add_uid`),
            KEY `appid` (`appid`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_cdk_user` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `gid` bigint(20) NOT NULL,
            `type` enum('vip','fen','addsn') NOT NULL,
            `cdk` varchar(64) NOT NULL,
            `val` bigint(10) NOT NULL,
            `note` varchar(64) DEFAULT NULL,
            `use_uid` bigint(20) DEFAULT NULL,
            `use_time` bigint(10) DEFAULT NULL,
            `use_ip` varchar(45) DEFAULT NULL,
            `add_role` enum('admin','agent') NOT NULL,
            `add_uid` bigint(20) DEFAULT NULL,
            `add_price` float(10,2) DEFAULT '0.00',
            `add_time` bigint(10) NOT NULL,
            `add_ip` varchar(45) DEFAULT NULL,
            `out_state` enum('y','n') DEFAULT 'n',
            `out_time` bigint(10) DEFAULT NULL,
            `state` enum('y','n') DEFAULT 'y',
            `appid` bigint(20) NOT NULL,
            PRIMARY KEY (`id`),
            UNIQUE KEY `cdk` (`cdk`,`appid`),
            KEY `gid` (`gid`),
            KEY `appid` (`appid`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_app_function` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `name` varchar(64) NOT NULL,
            `code` text NOT NULL,
            `notes` varchar(255) DEFAULT '',
            `allow` tinyint(1) DEFAULT 0,
            `fen` int(10) DEFAULT 0,
            `state` enum('y','n') DEFAULT 'y',
            `appid` bigint(20) unsigned NOT NULL,
            PRIMARY KEY (`id`),
            UNIQUE KEY `name_appid` (`name`, `appid`),
            KEY `appid` (`appid`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_app_ver` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `name` varchar(64) DEFAULT NULL,
            `ver_key` varchar(12) DEFAULT 'default',
            `ver_major` int(3) DEFAULT '1',
            `ver_minor` int(3) DEFAULT '0',
            `ver_patch` int(3) DEFAULT '0',
            `ver_state` enum('on','off') DEFAULT 'on',
            `ver_off_msg` varchar(255) DEFAULT NULL,
            `ver_url` varchar(128) DEFAULT NULL,
            `ver_content` text,
            `mid` bigint(20) DEFAULT NULL,
            `discard` tinyint(1) DEFAULT '0',
            `appid` bigint(20) NOT NULL,
            PRIMARY KEY (`id`),
            KEY `appid` (`appid`),
            KEY `ver_key_appid` (`ver_key`,`appid`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_app_notice` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `aid` bigint(20) NOT NULL,
            `visit` bigint(10) DEFAULT '0',
            `content` text NOT NULL,
            `time` bigint(10) NOT NULL,
            `appid` bigint(20) DEFAULT NULL,
            PRIMARY KEY (`id`),
            KEY `aid` (`aid`),
            KEY `appid` (`appid`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_app_blocklist` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `type` enum('ip','sn') NOT NULL,
            `val` varchar(64) NOT NULL,
            `time` bigint(10) NOT NULL,
            `appid` bigint(20) DEFAULT NULL,
            PRIMARY KEY (`id`),
            UNIQUE KEY `type_val_appid` (`type`,`val`,`appid`),
            KEY `appid` (`appid`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_app_extend` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `name` varchar(128) NOT NULL,
            `var_key` varchar(64) NOT NULL,
            `var_val` text NOT NULL,
            `appid` bigint(20) DEFAULT NULL,
            PRIMARY KEY (`id`),
            KEY `appid` (`appid`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_app_mi` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `name` varchar(64) NOT NULL,
            `type` varchar(24) NOT NULL,
            `config` json NOT NULL,
            `sign` enum('y','n') DEFAULT 'n',
            `time` int(10) DEFAULT '60',
            `appid` bigint(20) DEFAULT NULL,
            PRIMARY KEY (`id`),
            KEY `appid` (`appid`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_fen_event` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `name` varchar(128) NOT NULL,
            `fen` bigint(10) DEFAULT '0',
            `vip` bigint(10) DEFAULT '0',
            `vip_free` enum('y','n') DEFAULT 'n',
            `state` enum('on','off') DEFAULT 'on',
            `appid` bigint(20) NOT NULL,
            PRIMARY KEY (`id`),
            KEY `appid` (`appid`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_fen_order` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `fid` bigint(20) NOT NULL,
            `uid` bigint(20) NOT NULL,
            `name` varchar(128) NOT NULL,
            `mark` varchar(255) DEFAULT NULL,
            `fen` bigint(10) DEFAULT '0',
            `vip` bigint(10) DEFAULT '0',
            `time` bigint(10) NOT NULL,
            `appid` bigint(20) NOT NULL,
            PRIMARY KEY (`id`),
            KEY `uid` (`uid`),
            KEY `mark` (`mark`),
            KEY `appid` (`appid`),
            KEY `fid` (`fid`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
    r#"CREATE TABLE IF NOT EXISTS `t_settings` (
            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            `key` varchar(128) NOT NULL,
            `value` text DEFAULT NULL,
            PRIMARY KEY (`id`),
            UNIQUE KEY `key` (`key`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"#,
];

#[tokio::test]
async fn e2e_install_ddl_translates_and_runs() {
    let pool = SqlitePoolOptions::new()
        .max_connections(1)
        .connect("sqlite::memory:")
        .await
        .expect("SQLite 内存库连接失败");

    let mut total_stmts = 0usize;
    for (i, mysql_ddl) in TABLES.iter().enumerate() {
        let translated = adapt_ddl_mysql_to_sqlite(mysql_ddl)
            .unwrap_or_else(|e| panic!("表 #{} 转换失败: {}\n原始: {}", i, e, mysql_ddl));
        for stmt in &translated {
            sqlx::query(stmt).execute(&pool).await.unwrap_or_else(|e| {
                panic!("表 #{} 语句执行失败: {}\nSQL: {}\n原始: {}", i, e, stmt, mysql_ddl);
            });
            total_stmts += 1;
        }
    }

    // 验证 21 张表都创建成功
    let tables: Vec<String> = sqlx::query_scalar("SELECT name FROM sqlite_master WHERE type='table'")
        .fetch_all(&pool).await.unwrap();
    let tables: Vec<_> = tables.into_iter().filter(|n| !n.starts_with("sqlite_")).collect();
    assert_eq!(tables.len(), 21, "应创建 21 张表，实际: {tables:?}");
    assert!(total_stmts >= 21, "至少 21 条语句，实际 {total_stmts}");
}